### ISSUE TITLE
无法设置 iOS 推送开发环境

### ISSUE THREAD

**Issue by mintzhao** [DeanThompson/jpush-api-go-client#1]
比如我想给ios的开发环境发推送，必须设置option的Apns_production为false，如果不传，默认true。但是你的json序列化tag里设置omitempty，这个表示默认值就不传递。恰好，bool的默认值为false，所以怎么给开发环境发推送都不得行。。。

**Comment by DeanThompson** [comment]
多谢反馈，我明天修复一下，也欢迎提交 pull request :grimacing:

BTW，修改了一下标题。
